//
// Created by Damien Laidin on 22/10/2019.
//

#ifndef INTERVIEW_TRAINING_STRING_COMPRESSION_H
#define INTERVIEW_TRAINING_STRING_COMPRESSION_H

char *compress_string(char *str);

#endif //INTERVIEW_TRAINING_STRING_COMPRESSION_H
